#ifndef _GB_CONFIG_H
 #define _GB_CONFIG_H

 //GPIO PS/2 Keyboard Data
 #define KEYBOARD_DATA 32
 //GPIO PS/2 Keyboard CLK
 #define KEYBOARD_CLK 33


 //Fast DigitalWrite, DigitalRead
 //#define PS2_FAST_BIT

 //Time delay before init keyb
 #define PS2_BOOT_TIME_DELAY 1000
 
 //Auto detection Protocol Switching USB PS/2 (fix Perixx, Holtek, Cypres)
 //#define PS2_DIAGNOSTIC_ECHO
 
 //Time delay before send ECHO
 #define PS2_DIAGNOSTIC_ECHO_BOOT_TIME_DELAY 1000
 //Time delay after send ECHO
 #define PS2_DIAGNOSTIC_ECHO_TIME_DELAY 500
 //Timeout flag keyboard
 #define PS2_DIAGNOSTIC_ECHO_TIMEOUT 1000

 
 
 //IMPORTANT!!! Do not delete. Required for PS2_FAST_BIT (GPIO upper 32)
 #if KEYBOARD_DATA > 31
  #define KEYBOARD_DATA_END (KEYBOARD_DATA - 32)
  #define GPIO_IN_REG_KEYBOARD_DATA_END GPIO_IN1_REG
  #define GPIO_ENABLE_W1TS_REG_KEYBOARD_DATA_END GPIO_ENABLE1_W1TS_REG
  #define GPIO_OUT_W1TC_REG_KEYBOARD_DATA_END GPIO_OUT1_W1TC_REG
  #define GPIO_ENABLE_W1TC_REG_KEYBOARD_DATA_END GPIO_ENABLE1_W1TC_REG
 #else
  #define KEYBOARD_DATA_END KEYBOARD_DATA
  #define GPIO_IN_REG_KEYBOARD_DATA_END GPIO_IN_REG
  #define GPIO_ENABLE_W1TS_REG_KEYBOARD_DATA_END GPIO_ENABLE_W1TS_REG
  #define GPIO_OUT_W1TC_REG_KEYBOARD_DATA_END GPIO_OUT_W1TC_REG
  #define GPIO_ENABLE_W1TC_REG_KEYBOARD_DATA_END GPIO_ENABLE_W1TC_REG
 #endif

 #if KEYBOARD_CLK > 31
  #define KEYBOARD_CLK_END (KEYBOARD_CLK - 32)
  #define GPIO_IN_REG_KEYBOARD_CLK_END GPIO_IN1_REG
  #define GPIO_ENABLE_W1TS_REG_KEYBOARD_CLK_END GPIO_ENABLE1_W1TS_REG
  #define GPIO_OUT_W1TC_REG_KEYBOARD_CLK_END GPIO_OUT1_W1TC_REG
  #define GPIO_ENABLE_W1TC_REG_KEYBOARD_CLK_END GPIO_ENABLE1_W1TC_REG
 #else
  #define KEYBOARD_CLK_END KEYBOARD_CLK
  #define GPIO_IN_REG_KEYBOARD_CLK_END GPIO_IN_REG
  #define GPIO_ENABLE_W1TS_REG_KEYBOARD_CLK_END GPIO_ENABLE_W1TS_REG
  #define GPIO_OUT_W1TC_REG_KEYBOARD_CLK_END GPIO_OUT_W1TC_REG
  #define GPIO_ENABLE_W1TC_REG_KEYBOARD_CLK_END GPIO_ENABLE_W1TC_REG
 #endif 
 
#endif
 
